drop database if exists catfacts;
create database catfacts;
drop user if exists catuser;
create user catuser with encrypted password 'catuserpassword';
grant all privileges on database catfacts to catuser;
\c catfacts;
drop table if exists facts;
CREATE TABLE facts(id SERIAL, fact TEXT NOT NULL);
insert into facts(fact) values ('The penalty for killing a cat, 4,000 years ago in Egypt, was death.');
insert into facts(fact) values ('95% of all cat owners admit they talk to their cats.');
insert into facts(fact) values ('More cats are left-pawed than right-pawed. Out of 100 cats approximately 40 are left-pawed, 20 are right-pawed, and 40 are ambidextrous.');
insert into facts(fact) values ('A cat can jump as much as seven times its height.');
insert into facts(fact) values ('A cat cannot see directly under its nose. This is why the cat cannot seem to find tidbits on the floor.');
insert into facts(fact) values ('A cat has 230 bones in its body. A human only has 206 bones.');
insert into facts(fact) values ('A cat has four rows of whiskers.');
insert into facts(fact) values ('A frightened cat can run at speeds of up to 31 mph (50 km/h), slightly faster than a human sprinter.');
insert into facts(fact) values ('A cat sees about six times better than a human at night because of the tapetum lucidum, a layer of extra reflecting cells which absorb light.');
insert into facts(fact) values ('A cats whiskers, called vibrissae, grow on the cats face and on the back of its forelegs.');
insert into facts(fact) values ('Cat whiskers act as feelers or antennae, helping the animal to judge the precise width of any passage.');
insert into facts(fact) values ('A cat will almost never meow at another cat. Cats use this sound for humans.');
insert into facts(fact) values ('A cat will clean itself with paw and tongue after a dangerous experience or when it has fought with another cat.');
insert into facts(fact) values ('A cat will spend nearly 30% of its life grooming itself.');
insert into facts(fact) values ('A cats brain is more similar to a humans brain than that of a dog.');
insert into facts(fact) values ('Cats have 32 muscles that control the outer ear (compared to humans 6 muscles each). A cat can rotate its ears independently 180 degrees.');
insert into facts(fact) values ('Cats can hear sounds as high-pitched as 65 kHz; a humans hearing stops at just 20 kHz.');
insert into facts(fact) values ('A cats normal pulse is 140-240 beats per minute, with an average of 195.');
insert into facts(fact) values ('A cats jaws cannot move sideways.');
insert into facts(fact) values ('A cats normal body temperature is 101.5 degrees F (38.6 C).');
insert into facts(fact) values ('A cats sense of taste is keener than a dogs sense of taste.');
insert into facts(fact) values ('A cats tail held high means happiness. A twitching tail is a warning sign, and a tail tucked in close to the body is a sure sign of insecurity.');
insert into facts(fact) values ('A cats tail plays a vital part in the cats balance and in the "righting reflex" that allows it to land on its feet after falling from a height.');
insert into facts(fact) values ('A cats tongue is scratchy because its lined with papillae-tiny elevated backwards hooks that help to hold prey in place.');
insert into facts(fact) values ('A female cat can begin mating when she is between 5 and 9 months old.');
insert into facts(fact) values ('A male cat can begin mating when he is between 7 and 10 months old.');
insert into facts(fact) values ('A group of kittens is called a kindle; a group of adult cats form a clowder.');
insert into facts(fact) values ('A large majority of white cats with blue eyes are deaf. White cats with only one blue eye are deaf only in the ear closest to the blue eye.');
insert into facts(fact) values ('Adult cats with no health problems are in deep sleep 15 percent of their lives. They are in light sleep 50 percent of the time.');
insert into facts(fact) values ('Cats are only awake 6-8 hours a day.');
insert into facts(fact) values ('After being handled, cats lick themselves to smooth their fur and get rid of the "human" smell.');
insert into facts(fact) values ('Cats have 30 teeth (12 incisors, 10 premolars, 4 canines, and 4 molars).');
insert into facts(fact) values ('Kittens have baby teeth, which are replaced by permanent teeth around the age of 7 months.');
insert into facts(fact) values ('Both humans and cats have identical regions in the brain responsible for emotion.');
insert into facts(fact) values ('Multi-colored male cats are very rare. For every 3,000 tortoiseshell or calico cats born, only one will be male.');
insert into facts(fact) values ('Cat families usually play best in even numbers. Cats and kittens should be acquired in pairs whenever possible.');
insert into facts(fact) values ('Cat urine glows under a black light.');
insert into facts(fact) values ('Cats are attracted to automobile antifreeze because of its sweet taste.');
insert into facts(fact) values ('Cats are sometimes born with extra toes. This is called polydactyl.');
insert into facts(fact) values ('The cats front paw has 5 toes, but the back paws have 4.');
insert into facts(fact) values ('Cats are the only domestic animals that walk directly on their claws, not on their paws.');
insert into facts(fact) values ('Cats bury their feces to cover their trails from predators.');
insert into facts(fact) values ('Cats have AB blood groups just like people.');
insert into facts(fact) values ('Cats can get bored. They show their boredom by excessive licking, chewing, or biting.');
insert into facts(fact) values ('Cats can have freckles. They can appear anywhere on a cats skin and even in its mouth.');
insert into facts(fact) values ('Cats can learn tricks. They just sometimes choose not to.');
insert into facts(fact) values ('Cats can see color. Studies have shown that cats can distinguish between red, green, blue, yellow, and gray.');
insert into facts(fact) values ('Cats can see up to 120 feet away. Their peripheral vision is about 285 degrees.');
insert into facts(fact) values ('Cats have 13 ribs.');
insert into facts(fact) values ('Like birds, cats have a homing ability that uses its biological clock, the angle of the sun, and the Earths magnetic field.');
insert into facts(fact) values ('Cats have a third eyelcalled a haw, that is rarely visible. If it can be seen, it could be an indication of ill health.');
insert into facts(fact) values ('Cats have about 100 different vocalization sounds. In comparison, dogs have about 10.');
insert into facts(fact) values ('Cats have better memories than dogs.');
insert into facts(fact) values ('Cats have carpal pads on their front paws that help to prevent them from sliding on a slippery surface when jumping.');
insert into facts(fact) values ('Cats have true fur, meaning that they have both an undercoat and an outer coat.');
insert into facts(fact) values ('Cats lack a true collarbone and can generally squeeze their bodies through any space they can get their heads through.');
insert into facts(fact) values ('Cats love to hear the sound of their own name and your voice, so talk to them often.');
insert into facts(fact) values ('Cats must have fat in their diet, because they cant produce it on their own.');
insert into facts(fact) values ('Cats only need a sixth the amount of light that humans do to see. However, their daytime vision is only fair compared to that of humans.');
insert into facts(fact) values ('Cats purr at about 26 cycles per second, the same frequency as an idling diesel engine.');
insert into facts(fact) values ('Cats scratch to shed the sheaths of their old claws.');
insert into facts(fact) values ('Cat have 500 skeletal muscles (humans have 650).');
insert into facts(fact) values ('Cats with white fur and skin on their ears are very prone to sunburn.');
insert into facts(fact) values ('Cats, not dogs, are the most common pets in America . There are approximately 66 million cats to 58 million dogs.');
insert into facts(fact) values ('The average cat consumes about 127,750 calories a year, nearly 28 times its own weight in food and the same amount again in liquids.');
insert into facts(fact) values ('Each day in the US, animal shelters are forced to destroy 30,000 dogs and cats.');
insert into facts(fact) values ('Ear furnishings are the hairs that grow inside a cats ears.');
insert into facts(fact) values ('Human painkillers such acetaminophen (Tylenol) are toxic to cats. Chocolate is also poisonous to cats.');
insert into facts(fact) values ('A female cat may have three to seven kittens every four months. This is why population control using spaying and neutering is so important.');
insert into facts(fact) values ('If your cat is in the habit of rolling over and exposing his stomach, you can be sure he feels perfectly safe with you.');
insert into facts(fact) values ('In addition to using their noses, cats can smell with the Jacobsons organ which is located in the upper surface of the mouth.');
insert into facts(fact) values ('In ancient Egypt, the entire family would shave their eyebrows off as a sign of mourning when the family cat died.');
insert into facts(fact) values ('In general, cats live longer than most dogs. An average life span might be 12 to 14 years. Some cats are reaching 20 or more.');
insert into facts(fact) values ('In relation to their body size, cats have the largest eyes of any mammal.');
insert into facts(fact) values ('Stroking a cat can help to relieve stress, and the feel of a purring cat on your lap conveys a strong sense of security and comfort.');
insert into facts(fact) values ('Owning a cat can increase your overall health and decrease the occurrence of high blood pressure and other illnesses.');
insert into facts(fact) values ('Many cats are unable to properly digest cows milk. Milk and milk products give them diarrhea.');
insert into facts(fact) values ('Almost 10% of a cats bones are in its tail.');
insert into facts(fact) values ('More than 30 percent of American households have a cat as part of the family.');
insert into facts(fact) values ('Neutering a cat extends its life span by two or three years.');
insert into facts(fact) values ('Never pick a kitten up by the neck. Only a mother cat may do this safely.');
insert into facts(fact) values ('Newborn kittens have closed ear canals that dont begin to open for nine days.');
insert into facts(fact) values ('One litter box per cat, plus an extra box, is the best formula for a multi-cat household.');
insert into facts(fact) values ('Mother cats teach their kittens to use the litter box.');
insert into facts(fact) values ('The ancestor of all domestic cats is the African Wild Cat, which still exists today.');
insert into facts(fact) values ('The average canned or dry cat meal is the nutritional equivalent of eating five mice.');
insert into facts(fact) values ('The cat family split from the other mammals at least 40 million years ago, making them one of the oldest mammalian families.');
insert into facts(fact) values ('The cat lover is an ailurophile, while a cat hater is an ailurophobe.');
insert into facts(fact) values ('The cat was domesticated over 4,000 years ago. Todays house cats are descended from wildcats in Africa and Europe .');
insert into facts(fact) values ('The catgut formerly used as strings in tennis rackets and musical instruments does not come from cats.');
insert into facts(fact) values ('The color of the points in Siamese cats is heat related. Cool areas are darker.');
insert into facts(fact) values ('Siamese kittens are born white because of the heat inside the mothers uterus before birth.');
insert into facts(fact) values ('The declawing of a pet cat involves surgery called an onychectomy, which is the equivalent of cutting a humans fingers off at the knuckle.');
insert into facts(fact) values ('The different types of tabby patterns that are seen in domestic cats also occur in wild cats.');
insert into facts(fact) values ('The giraffe, camel, and cat are the only animals that walk by both their left feet, then both their right feet when walking.');
insert into facts(fact) values ('The heaviest cat ever recorded weighed 46 lbs.');
insert into facts(fact) values ('The only domestic animal not mentioned in the Bible is the cat.');
insert into facts(fact) values ('The ancient Egyptians were the first civilisation to realise the cats potential as a vermin hunter and tamed cats to protect the corn supplies.');
insert into facts(fact) values ('Sir Isaac Newton is not only credited with the laws of gravity but is also credited with inventing the cat flap.');
insert into facts(fact) values ('Cats cant taste sweets.');
insert into facts(fact) values ('Americans spend more annually on cat food than on baby food.');
insert into facts(fact) values ('In 1987 cats overtook dogs as the number one pet in America.');
insert into facts(fact) values ('In Asia and England, black cats are considered lucky.');
insert into facts(fact) values ('When a domestic cat goes after mice, about one pounce in three results in a catch.');
insert into facts(fact) values ('Studies show that if a cat falls off the seventh floor of a building it is 30% less likely to survive than a cat that falls off the twentieth floor.');
insert into facts(fact) values ('Most cats have no eyelashes.');
insert into facts(fact) values ('The way you treat kittens in the early stages of its life will render its personality traits later in life.');
insert into facts(fact) values ('A form of AIDS exists in cats.');
insert into facts(fact) values ('People who are allergic to cats are actually allergic to cat saliva or to cat dander.');
insert into facts(fact) values ('In ancient Egypt, mummies were made of cats, and embalmed mice were placed with them in their tombs.');
insert into facts(fact) values ('In the Middle Ages, during the Festival of Saint John, cats were burned alive in town squares.');
insert into facts(fact) values ('Today there are about 100 distinct breeds of the domestic cat.');
insert into facts(fact) values ('When cats are asleep, they are still alert to incoming stimuli. If you poke the tail of a sleeping cat, it will respond accordingly.');
insert into facts(fact) values ('The chlorine in fresh tap water irritates sensitive parts of the cats nose. Let tap water sit for 24 hours before giving it to a cat.');
insert into facts(fact) values ('Cats purr to communicate. Purring does not always mean happiness.');
insert into facts(fact) values ('A cat is pregnant for about 58-65 days.');
insert into facts(fact) values ('A cats hearing is much more sensitive than humans and dogs.');
insert into facts(fact) values ('Cats sleep 16 to 18 hours per day.');
insert into facts(fact) values ('A kittens eyes are always blue at first.');
insert into facts(fact) values ('If a male cat is both orange and black it is most likely sterile.');
insert into facts(fact) values ('There are tiny, parasitic worms that can live in a cats stomach. These worms cause frequent vomiting.');
insert into facts(fact) values ('Cats have 30 vertebrae - 5 more than humans have.');
insert into facts(fact) values ('A cats field of vision is about 185 degrees.');
insert into facts(fact) values ('A cat has a total of 24 whiskers, 4 rows of whiskers on each side. The upper two rows can move independently of the bottom two rows.');
insert into facts(fact) values ('A kitten will typically weigh about 3 ounces at birth. The typical male housecat will weigh between 7-9 pounds, slightly less for female housecats.');
insert into facts(fact) values ('Cats take between 20-40 breaths per minute.');
insert into facts(fact) values ('Cats lose almost as much fluid in the saliva while grooming themselves as they do through urination.');
insert into facts(fact) values ('The domestic cat is the only species able to hold its tail vertically while walking.');
insert into facts(fact) values ('Female felines are "superfecund," which means that each of the kittens in her litter can have a different father.');
insert into facts(fact) values ('Cat saliva contains a detergent that keeps their fur clean.');
insert into facts(fact) values ('Cats eyes dont glow in the dark; they only reflect light.');
insert into facts(fact) values ('Cats born without tails genetically have a shorter spine and longer rear legs than other cats.');
insert into facts(fact) values ('Cats eat grass to keep their digestive systems clean. The regurgitation brings up hair and other irritants.');
insert into facts(fact) values ('Cats are able to hear sounds that move faster than 45,000 hertz. They could hear the sound of a bat.');
insert into facts(fact) values ('There are approximately 60,000 hairs per square inch on the back of a cat and about 120,000 per square inch on its underside.');
insert into facts(fact) values ('The largest cat breed is the Ragdoll. Males weigh 12-20 pounds, with females weighing 10-15 pounds.');
insert into facts(fact) values ('The smallest cat breed is the Singapura. Males weigh about 6 pounds while females weigh about 4 pounds.');
insert into facts(fact) values ('Cats dont see "detail" very well. To them, their person may appear hazy when standing in front of them.');
insert into facts(fact) values ('Kittens begin dreaming at just over one week old.');
insert into facts(fact) values ('If an overweight cats "sides" stick out further than her whiskers, she will lose her sense of perception and stability.');
insert into facts(fact) values ('Every cats nose pad is unique, and no two nose prints are the same.');
insert into facts(fact) values ('About 37% of American homes today have at least 1 cat.');
insert into facts(fact) values ('The catnip plant contains an oil called hepetalactone which does for cats what marijuana does to some people. Catnip is non-addictive.');
insert into facts(fact) values ('Not every cat gets "high" from catnip. If the cat doesnt have a specific gene, it wont react (about 20% do not have the gene).');
insert into facts(fact) values ('When well treated, a cat can live twenty or more years.');
insert into facts(fact) values ('Cats are subject to gum disease and to dental caries. They should have their teeth cleaned by the vet or the cat dentist once a year.');
insert into facts(fact) values ('Cats can get tapeworms from eating mice. If your cat catches a mouse it is best to take the prize away from it.');
insert into facts(fact) values ('If a cat is frightened, the hair stands up fairly evenly all over the body.');
insert into facts(fact) values ('Cats respond most readily to names that end in an "ee" sound.');
insert into facts(fact) values ('A female cat reaches sexual maturity within 6 to 10 months.');
insert into facts(fact) values ('A male cat usually reaches sexual maturity between 9 and 12 months.');
insert into facts(fact) values ('A cat will tremble or shiver when it is in extreme pain.');
insert into facts(fact) values ('The average lifespan of an outdoor-only (feral and non-feral) is about 3 years; an indoor-only cat can live 16 years and longer.');
insert into facts(fact) values ('Cats with long, lean bodies are more likely to be outgoing, and more protective and vocal than those with a stocky build.');
insert into facts(fact) values ('A steady diet of dog food may cause blindness in your cat - it lacks taurine.');
insert into facts(fact) values ('An estimated 50% of todays cat owners never take their cats to a veterinarian for health care.');
insert into facts(fact) values ('Most cats adore sardines.');
insert into facts(fact) values ('Cats respond better to women than to men, probably due to the fact that womens voices have a higher pitch.');
insert into facts(fact) values ('When your cats rubs up against you, she is marking you as "hers" with her scent.');
insert into facts(fact) values ('Cat bites are more likely to become infected than dog bites - but human bites are the most dangerous of all.');
insert into facts(fact) values ('Dont be alarmed when your cats bring you gifts of birds, mice or other wild critters. This is a gift, and they do it to please you.');
insert into facts(fact) values ('A smooth, shiny coat is the sign of a healthy cat.');
insert into facts(fact) values ('A healthy kitten has clear, bright eyes and clean ears.');
insert into facts(fact) values ('If your cat hides and then runs out and pounces on you, she is acting out her instinctive hunting ritual.');
insert into facts(fact) values ('Cats lick people as a sign of affection.');
insert into facts(fact) values ('Most lively, active kittens grow up to be friendly, outgoing cats.');
insert into facts(fact) values ('A healthy cats nose is cool.');
insert into facts(fact) values ('When a cat swishes its tail back and forth, shes concentrating on somthing; if her tail starts moving faster, she has become annoyed.');
insert into facts(fact) values ('Brushing your cat daily will cut down on hairballs.');
insert into facts(fact) values ('If you do not respond when your cat talks to you, it will soon lose the urge to communicate with you.');
insert into facts(fact) values ('Some cats, males in particular, develop health problems if fed dry food exclusively.');
insert into facts(fact) values ('A little vegetable oil daily will help to prevent fur-balls and bring a shine to your cats coat.');
insert into facts(fact) values ('In multi-cat households, cats of the opposite sex usually get along better.');
insert into facts(fact) values ('25% of cat owners blow dry their cats hair after a bath.');
insert into facts(fact) values ('If your cat is near you, and her tail is quivering, this is the greatest expression of love your cat can give you.');
insert into facts(fact) values ('"Sociable" cats will follow you from room to room to monitor your activities throughout the day.');
insert into facts(fact) values ('The more cats are spoken to, the more they will speak to you.');
insert into facts(fact) values ('Most cats prefer their food at room temperature.');
insert into facts(fact) values ('A cat that bites you after you have rubbed his stomach, is probably biting out of pleasure, not anger.');
insert into facts(fact) values ('It costs $7000 to care for one household cat over its lifetime. This covers only the necessities; the pampered pet will carry a higher price.');
insert into facts(fact) values ('Cats lived with soldiers in trenches, where they killed mice during World War I.');
insert into facts(fact) values ('Napoleon was terrified of cats.');
insert into facts(fact) values ('Abraham Lincoln loved cats. He had four of them while he lived in the White House.');
insert into facts(fact) values ('The cat family split from the other mammals at least 40,000,000 years ago, making them one of the oldest mammalian families.');
insert into facts(fact) values ('Phoenician cargo ships are thought to have brought the first domesticated cats to Europe in about 900 BC.');
insert into facts(fact) values ('Cats have been domesticated for half as long as dogs have been.');
insert into facts(fact) values ('The Pilgrims were the first to introduce cats to North America.');
insert into facts(fact) values ('The first breeding pair of Siamese cats arrived in England in 1884.');
insert into facts(fact) values ('The first formal cat show was held in England in 1871; in America, in 1895.');
insert into facts(fact) values ('The Maine Coon cat is Americas only natural breed of domestic feline.');
insert into facts(fact) values ('The life expectancy of cats has nearly doubled since 1930 - from 8 to 16 years.');
insert into facts(fact) values ('Cat litter was "invented" in 1947 when Edward Lowe asked his neighbor to try a dried, granulated clay used to sop up grease spills in factories.');
insert into facts(fact) values ('Genetic mutation created the domestic cat which is tame from birth.');
insert into facts(fact) values ('Cats can be taught to use a toilet, come, sit, beg, heel, jump through a hoop, play dead, roll over, open a door, shake, fetch and more.');
insert into facts(fact) values ('A cat will not eat its food if is unable to smell it.');
insert into facts(fact) values ('34% of cat-owning households have incomes of $60,000 or more.');
insert into facts(fact) values ('32% of those who own their own home, also own at least one cat.');
insert into facts(fact) values ('If your cat rolls over on his back to expose his belly, it means he trusts you.');
insert into facts(fact) values ('Contrary to popular belief, the cat is a social animal. A pet cat will respond and answer to speech, and seems to enjoy human companionship.');
insert into facts(fact) values ('Some cats will actually knead and drool when they are petted. The kneading or marching means that the cat is happy.');
insert into facts(fact) values ('Unlike humans and dogs, cats do not suffer a lot from loneliness. They are far more concerned with territorial issues.');
insert into facts(fact) values ('Hunting is not instinctive for cats. Kittens born to non-hunting mothers may never learn to hunt.');
insert into facts(fact) values ('Cats are attracted to the cave-like appeal of a clothes dryer.');
insert into facts(fact) values ('A cat will kill its prey based on movement, but may not necessarily recognize prey as food. Realizing that prey is food is a learned behavior.');
insert into facts(fact) values ('Most deaf cats do not meow.');
insert into facts(fact) values ('In England, the government owns thousands of cats. Their job is to help keep the buildings free of rodents.');
insert into facts(fact) values ('The word cat refers to a family of meat-eating animals that include tigers, lions, leopards, and panthers.');
insert into facts(fact) values ('You can tell a cats mood by looking into its eyes. A frightened or excited cat will have large, round pupils.');
insert into facts(fact) values ('The cats footpads absorb the shocks of the landing when the cat jumps.');
insert into facts(fact) values ('Cats dont kill their prey with their claws, the claws are used to hold onto the prey, the teeth are used to kill the prey.');
insert into facts(fact) values ('The claws on the cats back feet arent as sharp as the claws on the front feet because they cant retract into the toe.');
insert into facts(fact) values ('Cats perspire through their paws.');
insert into facts(fact) values ('Cats, especially older cats, do get cancer. Many times this disease can be treated successfully.');
insert into facts(fact) values ('Some common houseplants are poisonous to cats, such as: English Ivy, iris, mistletoe, philodendron, and yew.');
insert into facts(fact) values ('Though rare, cats can contract canine heart worms.');
insert into facts(fact) values ('Cats think that humans are big cats. This influences their behavior in many ways.');
insert into facts(fact) values ('Cats can be taught to walk on a leash, but a lot of time and patience is required to teach them.');
insert into facts(fact) values ('A happy cat holds her tail high and steady.');
insert into facts(fact) values ('Cats have individual preferences for scratching surfaces and angles. Some are horizontal scratchers while others exercise their claws vertically.');
insert into facts(fact) values ('All cats have three sets of long hairs that are sensitive to pressure - whiskers, eyebrows,and the hairs between their paw pads.');
insert into facts(fact) values ('When a cat drinks, its tongue - which has tiny barbs on it - scoops the liquid up backwards.');
insert into facts(fact) values ('Florence Nightingale owned more than 60 cats in her lifetime.');
insert into facts(fact) values ('If your cat pushes his face against your head, it is a sign of acceptance and affection.');
insert into facts(fact) values ('Tomcats can mate at anytime, while quenns can only mate during a period of time called heat or estrus.');
insert into facts(fact) values ('At 4 weeks, it is important to play with kittens so that they do not develope a fear of people.');
insert into facts(fact) values ('Kittens remain with their mother till the age of 9 weeks.');
insert into facts(fact) values ('It is estimated that cats can make over 60 different sounds.');
insert into facts(fact) values ('Cats often overract to unexpected stimuli because of their extremely sensitive nervous system.');
insert into facts(fact) values ('Kittens who are taken along on short, trouble-free car trips to town tend to make good passengers when they get older.');
insert into facts(fact) values ('Cats, just like people, are subject to asthma.');
insert into facts(fact) values ('Since cats are so good at hiding illness, even a single instance of a symptom should be taken very seriously.');
insert into facts(fact) values ('There is a species of cat smaller than the average housecat. Its top weight is 5.5 pounds.');
insert into facts(fact) values ('A tortoiseshell is black with red or orange markings and a calico is white with patches of red, orange and black.');
insert into facts(fact) values ('The Ancient Egyptian word for cat was mau, which means "to see".');
insert into facts(fact) values ('Cats that live together sometimes rub each others heads to show that they have no intention of fighting.');
insert into facts(fact) values ('Australia and Antarctica are the only continents which have no native cat species.');
insert into facts(fact) values ('A falling cat will always right itself in a precise order.');
insert into facts(fact) values ('It is believed that a white cat sitting on your doorstep just before your wedding is a sign of lasting happiness.');
insert into facts(fact) values ('Cats are more active during the evening hours.');
insert into facts(fact) values ('According to myth, a cat sleeping with all four paws tucked under means cold weather is coming.');
insert into facts(fact) values ('The average litter of kittens is between 2 - 6 kittens.');
insert into facts(fact) values ('All cats need taurine in their diet to avoid blindness. Cats must also have fat in their diet as they are unable to produce it on their own.');
insert into facts(fact) values ('Unlike humans, cats do not need to blink their eyes on a regular basis to keep their eyes lubricated.');
insert into facts(fact) values ('It may take as long as 2 weeks for a kitten to be able to hear well.');
insert into facts(fact) values ('Cats can judge within 3 inches the precise location of a sound being made 1 yard away.');
insert into facts(fact) values ('A cat has approximately 60 to 80 million olfactory cells (a human has between 5 and 20 million).');
insert into facts(fact) values ('Cats dislike citrus scent.');
insert into facts(fact) values ('Cats lap liquid from the underside of their tongue, not from the top.');
insert into facts(fact) values ('Domestic cats purr both when inhaling and when exhaling.');
insert into facts(fact) values ('The ancient Egyptians were the first to tame the cat (in about 3000 BC), and used them to control pests.');
insert into facts(fact) values ('In Siam, the cat was so revered that one rode in a chariot at the head of a parade celebrating the new king.');
insert into facts(fact) values ('Female cats are "polyestrous," which means they may have many heat periods over the course of a year.');
insert into facts(fact) values ('Many cats love having their forehead gently stroked.');
insert into facts(fact) values ('Cats come back to full alertness from the sleep state faster than any other creature.');
insert into facts(fact) values ('In an average year, cat owners in the United States spend over $2 billion on cat food.');
