FROM registry.redhat.io/devspaces/udi-rhel8@sha256:99ff1b5c541855e4cf368816c4bcdcdc86d32304023f72c4443213a4032ef05b

RUN dnf install postgresql-devel redhat-rpm-config python-devel -y

ENTRYPOINT [ "/entrypoint.sh" ]
CMD tail -f /dev/null
